apiVersion: apps/v1
kind: Deployment
metadata:
  name:  task
  namespace: default
  labels:
    app:  task
spec:
  selector:
    matchLabels:
      app: task
  replicas: 2
  template:
    metadata:
      labels:
        app:  task
    spec:
      containers:
      - name:  task
        image:  elshahat20/api:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
          name:  http
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name:  task
  namespace: default
spec:
  selector:
    app:  task
  ports:
    - name:  http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer