apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ${APP_NAME}
  namespace: default
  labels:
    app:  ${APP_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  replicas: 2
  template:
    metadata:
      labels:
        app:  ${APP_NAME}
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name:  ${APP_NAME}
        image:  $DOCKER_REPO:${IMAGE_TAG}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
          name:  http
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name:  ${APP_NAME}
  namespace: default
spec:
  selector:
    app:  ${APP_NAME}
  ports:
    - name:  http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer